#!/bin/sh
INPUT="$(echo $1 | sed 's/[^.0-9/]//g')"
COMMENT="$2"
if [ "x$COMMENT" == "x" ]
then
        iptables -D BLOCK -s $INPUT -j DROP
else
        iptables -D BLOCK -s $INPUT -m comment --comment "$COMMENT" -j DROP
fi
/usr/local/sbin/blocklist

